name: Check Branch Name

on: [push, pull_request]

jobs:
  check-branch:
    runs-on: codeberg-medium
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Check branch name
        env:
          CI_EVENT_NAME: ${{ forgejo.event_name }}
          CI_HEAD_REF: ${{ forgejo.head_ref }}
          CI_REF: ${{ forgejo.ref }}
        run: bash scripts/check_branch_name.sh
