name: Check Branch Name

on: [push, pull_request]

jobs:
  check-branch:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check branch name
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: bash scripts/check_branch_name.sh
