name: Setup Rust
description: Install Rust toolchain and restore cargo cache.

inputs:
  toolchain:
    description: Rust toolchain to install.
    default: stable

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: https://codeberg.org/wackbyte/rust-toolchain@trunk
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Cache cargo registry and git
      uses: https://data.forgejo.org/actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-registry-
